// <auto-generated />
using GroceryProducts.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GroceryProducts.Api.Migrations
{
    [DbContext(typeof(GroceryDbContext))]
    [Migration("20250130120951_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("grocery_products")
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GroceryProducts.Api.Entities.GroceryProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("brand");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_in_stock");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("slug");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_products_name");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_products_slug");

                    b.ToTable("products", "grocery_products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Fruits",
                            Description = "Fresh, juicy apples from local farms.",
                            Name = "Organic Apples",
                            Price = 1.50m,
                            QuantityInStock = 0,
                            Slug = "organic-apples"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Dairy",
                            Description = "1 gallon of fresh whole milk.",
                            Name = "Whole Milk",
                            Price = 3.99m,
                            QuantityInStock = 0,
                            Slug = "whole-milk"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Dairy",
                            Description = "A dozen fresh, organic brown eggs.",
                            Name = "Brown Eggs - 12 count",
                            Price = 4.50m,
                            QuantityInStock = 0,
                            Slug = "brown-eggs-12-count"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Fruits",
                            Description = "Ripe and ready to eat.",
                            Name = "Bananas",
                            Price = 0.50m,
                            QuantityInStock = 0,
                            Slug = "bananas"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Vegetables",
                            Description = "Fresh, crunchy carrots.",
                            Name = "Carrots",
                            Price = 0.75m,
                            QuantityInStock = 0,
                            Slug = "carrots"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Meat & Seafood",
                            Description = "Boneless, skinless chicken breast.",
                            Name = "Chicken Breast",
                            Price = 4.99m,
                            QuantityInStock = 0,
                            Slug = "chicken-breast"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Meat & Seafood",
                            Description = "Fresh salmon fillet.",
                            Name = "Salmon Fillet",
                            Price = 9.99m,
                            QuantityInStock = 0,
                            Slug = "salmon-fillet"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Dairy",
                            Description = "Sharp cheddar cheese.",
                            Name = "Cheddar Cheese",
                            Price = 3.50m,
                            QuantityInStock = 0,
                            Slug = "cheddar-cheese"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Dairy",
                            Description = "Plain yogurt.",
                            Name = "Yogurt",
                            Price = 2.00m,
                            QuantityInStock = 0,
                            Slug = "yogurt"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Bakery",
                            Description = "Freshly baked bread.",
                            Name = "Bread",
                            Price = 2.50m,
                            QuantityInStock = 0,
                            Slug = "bread"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Pantry",
                            Description = "Spaghetti pasta.",
                            Name = "Pasta",
                            Price = 1.25m,
                            QuantityInStock = 0,
                            Slug = "pasta"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Pantry",
                            Description = "Long grain rice.",
                            Name = "Rice",
                            Price = 1.75m,
                            QuantityInStock = 0,
                            Slug = "rice"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Pantry",
                            Description = "Extra virgin olive oil.",
                            Name = "Olive Oil",
                            Price = 5.99m,
                            QuantityInStock = 0,
                            Slug = "olive-oil"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Vegetables",
                            Description = "Fresh, ripe tomatoes.",
                            Name = "Tomatoes",
                            Price = 0.99m,
                            QuantityInStock = 0,
                            Slug = "tomatoes"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Vegetables",
                            Description = "Crisp lettuce.",
                            Name = "Lettuce",
                            Price = 1.25m,
                            QuantityInStock = 0,
                            Slug = "lettuce"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Meat & Seafood",
                            Description = "Tender beef steak.",
                            Name = "Beef Steak",
                            Price = 8.99m,
                            QuantityInStock = 0,
                            Slug = "beef-steak"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Meat & Seafood",
                            Description = "Fresh shrimp.",
                            Name = "Shrimp",
                            Price = 7.99m,
                            QuantityInStock = 0,
                            Slug = "shrimp"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Dairy",
                            Description = "2% milk.",
                            Name = "Milk",
                            Price = 3.00m,
                            QuantityInStock = 0,
                            Slug = "milk"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Dairy",
                            Description = "Unsalted butter.",
                            Name = "Butter",
                            Price = 2.75m,
                            QuantityInStock = 0,
                            Slug = "butter"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Bakery",
                            Description = "Freshly baked bagels.",
                            Name = "Bagels",
                            Price = 1.50m,
                            QuantityInStock = 0,
                            Slug = "bagels"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Pantry",
                            Description = "Breakfast cereal.",
                            Name = "Cereal",
                            Price = 3.25m,
                            QuantityInStock = 0,
                            Slug = "cereal"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Pantry",
                            Description = "Ground coffee.",
                            Name = "Coffee",
                            Price = 4.50m,
                            QuantityInStock = 0,
                            Slug = "coffee"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Pantry",
                            Description = "Black tea bags.",
                            Name = "Tea",
                            Price = 2.00m,
                            QuantityInStock = 0,
                            Slug = "tea"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Pantry",
                            Description = "Granulated sugar.",
                            Name = "Sugar",
                            Price = 1.75m,
                            QuantityInStock = 0,
                            Slug = "sugar"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Bakery",
                            Description = "Freshly baked whole wheat bread.",
                            Name = "Whole Wheat Bread",
                            Price = 2.75m,
                            QuantityInStock = 0,
                            Slug = "whole-wheat-bread"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
